
INSERT INTO logs_template (key, value, language) VALUES
    ('login', 'User %s with username %s logged in successfully at %s.', 'en'),
    ('login', 'کاربر %s با نام کاربری %s با موفقیت در ساعت %s وارد شد.', 'fa'),
    ('logout', 'User with id %s logged out successfully at %s.', 'en'),
    ('logout', 'کاربر  شناسه %s با موفقیت در ساعت %s از سیستم خارج شد.', 'fa'),
    ('createUser', 'A new user with name %s and username %s was created successfully by %s at %s.', 'en'),
    ('createUser', 'یک کاربر جدید با نام %s و نام کاربری %s با موفقیت توسط %s در ساعت %s ایجاد شد.', 'fa'),
    ('updateUser', 'User with name %s and username %s was updated successfully by %s at %s.', 'en'),
    ('updateUser', 'کاربر با نام %s و نام کاربری %s با موفقیت توسط %s در ساعت %s به‌روزرسانی شد.', 'fa'),
    ('getUser', 'User with name %s and username %s was retrieved successfully by %s at %s.', 'en'),
    ('getUser', 'اطلاعات کاربر با نام %s و نام کاربری %s با موفقیت توسط %s در ساعت %s بازیابی شد.', 'fa'),
    ('listUser', 'User %s listed %s users successfully at %s.', 'en'),
    ('listUser', 'کاربر %s موفق به لیست کردن %s کاربر در ساعت %s شد.', 'fa'),
    ('deleteUser', 'User %s deleted user with ID %s successfully at %s.', 'en'),
    ('deleteUser', 'کاربر %s کاربر با شناسه %s را با موفقیت در ساعت %s حذف کرد.', 'fa'),
    ('createProduct', 'User %s created product with name %s successfully at %s.', 'en'),
    ('createProduct', 'کاربر %s محصول با نام %s را با موفقیت در ساعت %s ایجاد کرد.', 'fa'),
    ('updateProduct', 'User %s updated product with name %s successfully at %s.', 'en'),
    ('updateProduct', 'کاربر %s محصول با نام %s را با موفقیت در ساعت %s به‌روزرسانی کرد.', 'fa'),
    ('getProduct', 'User %s retrieved product with name %s successfully at %s.', 'en'),
    ('getProduct', 'کاربر %s محصول با نام %s را با موفقیت در ساعت %s بازیابی کرد.', 'fa'),
    ('listProduct', 'User %s listed %s products successfully at %s.', 'en'),
    ('listProduct', 'کاربر %s موفق به لیست کردن %s محصول در ساعت %s شد.', 'fa'),
    ('deleteProduct', 'User %s deleted product with ID %s successfully at %s.', 'en'),
    ('deleteProduct', 'کاربر %s محصول با شناسه %s را با موفقیت در ساعت %s حذف کرد.', 'fa'),
    ('createCustomer', 'User %s created customer with name %s successfully at %s.', 'en'),
    ('createCustomer', 'کاربر %s مشتری با نام %s را با موفقیت در ساعت %s ایجاد کرد.', 'fa'),
    ('updateCustomer', 'User %s updated customer with name %s successfully at %s.', 'en'),
    ('updateCustomer', 'کاربر %s مشتری با نام %s را با موفقیت در ساعت %s به‌روزرسانی کرد.', 'fa'),
    ('getCustomer', 'User %s retrieved customer with name %s successfully at %s.', 'en'),
    ('getCustomer', 'کاربر %s مشتری با نام %s را با موفقیت در ساعت %s بازیابی کرد.', 'fa'),
    ('listCustomer', 'User %s listed %s customers successfully at %s.', 'en'),
    ('listCustomer', 'کاربر %s موفق به لیست کردن %s مشتری در ساعت %s شد.', 'fa'),
    ('deleteCustomer', 'User %s deleted customer with ID %s successfully at %s.', 'en'),
    ('deleteCustomer', 'کاربر %s مشتری با شناسه %s را با موفقیت در ساعت %s حذف کرد.', 'fa'),
    ('createCustomerProduct', 'User %s created customer-product relationship with customerID %s and productID %s successfully at %s.', 'en'),
    ('createCustomerProduct', 'کاربر %s ارتباط مشتری-محصول با customerID %s و productID %s را با موفقیت در ساعت %s ایجاد کرد.', 'fa'),
    ('updateCustomerProduct', 'User %s updated customer-product relationship with customerID %s and productID %s successfully at %s.', 'en'),
    ('updateCustomerProduct', 'کاربر %s ارتباط مشتری-محصول با customerID %s و productID %s را با موفقیت در ساعت %s به‌روزرسانی کرد.', 'fa'),
    ('getCustomerProduct', 'User %s retrieved customer-product relationship with customerID %s and productID %s successfully at %s.', 'en'),
    ('getCustomerProduct', 'کاربر %s ارتباط مشتری-محصول با customerID %s و productID %s را با موفقیت در ساعت %s بازیابی کرد.', 'fa'),
    ('listCustomerProduct', 'User %s listed %s customer-products successfully at %s.', 'en'),
    ('listCustomerProduct', 'کاربر %s موفق به لیست کردن %s ارتباط مشتری-محصول در ساعت %s شد.', 'fa'),
    ('deleteCustomerProduct', 'User %s deleted customer-product relationship with ID %s successfully at %s.', 'en'),
    ('deleteCustomerProduct', 'کاربر %s ارتباط مشتری-محصول با شناسه %s را با موفقیت در ساعت %s حذف کرد.', 'fa'),
    ('createRestriction', 'User %s created restriction with name %s and productID %s successfully at %s.', 'en'),
    ('createRestriction', 'کاربر %s محدودیت با نام %s و productID %s را با موفقیت در ساعت %s ایجاد کرد.', 'fa'),
    ('updateRestriction', 'User %s updated restriction with name %s and productID %s successfully at %s.', 'en'),
    ('updateRestriction', 'کاربر %s محدودیت با نام %s و productID %s را با موفقیت در ساعت %s به‌روزرسانی کرد.', 'fa'),
    ('getRestriction', 'User %s retrieved restriction with name %s and productID %s successfully at %s.', 'en'),
    ('getRestriction', 'کاربر %s محدودیت با نام %s و productID %s را با موفقیت در ساعت %s بازیابی کرد.', 'fa'),
    ('listRestriction', 'User %s listed %s restrictions for productID %s successfully at %s.', 'en'),
    ('listRestriction', 'کاربر %s موفق به لیست کردن %s محدودیت برای productID %s در ساعت %s شد.', 'fa'),
    ('deleteRestriction', 'User %s deleted restriction with ID %s successfully at %s.', 'en'),
    ('deleteRestriction', 'کاربر %s محدودیت با شناسه  %s را با موفقیت در ساعت %s حذف کرد.', 'fa');
