
INSERT INTO logs_template (key, value, language) VALUES
    ('login', 'User %s with username %s logged in successfully .', 'en'),
    ('login', 'کاربر %s با نام کاربری %s با موفقیت  وارد شد.', 'fa'),
    ('logout', 'User with id %s logged out successfully .', 'en'),
    ('logout', 'کاربر  شناسه %s با موفقیت  از سیستم خارج شد.', 'fa'),
    ('createUser', 'A new user with name %s and username %s was created successfully by %s .', 'en'),
    ('createUser', 'یک کاربر جدید با نام %s و نام کاربری %s با موفقیت توسط %s  ایجاد شد.', 'fa'),
    ('updateUser', 'User with name %s and username %s was updated successfully by %s .', 'en'),
    ('updateUser', 'کاربر با نام %s و نام کاربری %s با موفقیت توسط %s  به‌روزرسانی شد.', 'fa'),
    ('getUser', 'User with name %s and username %s was watched successfully by %s .', 'en'),
    ('getUser', 'اطلاعات کاربر با نام %s و نام کاربری %s با موفقیت توسط %s  مشاهده شد.', 'fa'),
    ('listUser', 'User %s watched %s users successfully .', 'en'),
    ('listUser', 'کاربر %s موفق به مشاهده کردن %s کاربر  شد.', 'fa'),
    ('deleteUser', 'User %s deleted user with ID %s successfully .', 'en'),
    ('deleteUser', 'کاربر %s کاربر با شناسه %s را با موفقیت  حذف کرد.', 'fa'),
    ('createProduct', 'User %s created product with name %s successfully .', 'en'),
    ('createProduct', 'کاربر %s محصول با نام %s را با موفقیت  ایجاد کرد.', 'fa'),
    ('updateProduct', 'User %s updated product with name %s successfully .', 'en'),
    ('updateProduct', 'کاربر %s محصول با نام %s را با موفقیت  به‌روزرسانی کرد.', 'fa'),
    ('getProduct', 'User %s watched product with name %s successfully .', 'en'),
    ('getProduct', 'کاربر %s محصول با نام %s را با موفقیت  مشاهده کرد.', 'fa'),
    ('listProduct', 'User %s watched %s products successfully .', 'en'),
    ('listProduct', 'کاربر %s موفق به مشاهده کردن %s محصول  شد.', 'fa'),
    ('deleteProduct', 'User %s deleted product with ID %s successfully .', 'en'),
    ('deleteProduct', 'کاربر %s محصول با شناسه %s را با موفقیت  حذف کرد.', 'fa'),
    ('createCustomer', 'User %s created customer with name %s successfully .', 'en'),
    ('createCustomer', 'کاربر %s مشتری با نام %s را با موفقیت  ایجاد کرد.', 'fa'),
    ('updateCustomer', 'User %s updated customer with name %s successfully .', 'en'),
    ('updateCustomer', 'کاربر %s مشتری با نام %s را با موفقیت  به‌روزرسانی کرد.', 'fa'),
    ('getCustomer', 'User %s watched customer with name %s successfully .', 'en'),
    ('getCustomer', 'کاربر %s مشتری با نام %s را با موفقیت  مشاهده کرد.', 'fa'),
    ('listCustomer', 'User %s watched %s customers successfully .', 'en'),
    ('listCustomer', 'کاربر %s موفق به مشاهده کردن %s مشتری  شد.', 'fa'),
    ('deleteCustomer', 'User %s deleted customer with ID %s successfully .', 'en'),
    ('deleteCustomer', 'کاربر %s مشتری با شناسه %s را با موفقیت  حذف کرد.', 'fa'),
    ('createCustomerProduct', 'User %s created customer-product relationship with customerID %s and productID %s successfully .', 'en'),
    ('createCustomerProduct', 'کاربر %s ارتباط مشتری-محصول با customerID %s و productID %s را با موفقیت  ایجاد کرد.', 'fa'),
    ('updateCustomerProduct', 'User %s updated customer-product relationship with customerID %s and productID %s successfully .', 'en'),
    ('updateCustomerProduct', 'کاربر %s ارتباط مشتری-محصول با customerID %s و productID %s را با موفقیت  به‌روزرسانی کرد.', 'fa'),
    ('getCustomerProduct', 'User %s watched customer-product relationship with customerID %s and productID %s successfully .', 'en'),
    ('getCustomerProduct', 'کاربر %s ارتباط مشتری-محصول با customerID %s و productID %s را با موفقیت  مشاهده کرد.', 'fa'),
    ('listCustomerProduct', 'User %s watched %s customer-products successfully .', 'en'),
    ('listCustomerProduct', 'کاربر %s موفق به مشاهده کردن %s ارتباط مشتری-محصول  شد.', 'fa'),
    ('deleteCustomerProduct', 'User %s deleted customer-product relationship with ID %s successfully .', 'en'),
    ('deleteCustomerProduct', 'کاربر %s ارتباط مشتری-محصول با شناسه %s را با موفقیت  حذف کرد.', 'fa'),
    ('createRestriction', 'User %s created restriction with name %s  successfully .', 'en'),
    ('createRestriction', 'کاربر %s محدودیت با نام %s را با موفقیت  ایجاد کرد.', 'fa'),
    ('updateRestriction', 'User %s updated restriction with name %s  successfully .', 'en'),
    ('updateRestriction', 'کاربر %s محدودیت با نام %s  را با موفقیت  به‌روزرسانی کرد.', 'fa'),
    ('getRestriction', 'User %s watched restriction with name %s successfully .', 'en'),
    ('getRestriction', 'کاربر %s محدودیت با نام %s را با موفقیت  مشاهده کرد.', 'fa'),
    ('listRestriction', 'User %s watched restrictions %s successfully .', 'en'),
    ('listRestriction', 'کاربر %s موفق به مشاهده کردن محدودیت %s شد.', 'fa'),
    ('deleteRestriction', 'User %s deleted restriction with ID %s successfully .', 'en'),
    ('deleteRestriction', 'کاربر %s محدودیت با شناسه  %s را با موفقیت  حذف کرد.', 'fa'),
    ('checkLicense', 'checked license for customer : %s and product : %s and license type : %s with %s expire time', 'en'),
    ('checkLicense', 'مجوز برای مشتری : %s و محصول : %s و نوع مجوز : %s با زمان انقضای %s بررسی شد', 'fa');

